# Site settings
title: Skymatic
description: >
  Skymatic develops encryption and IT security solutions and finds answers to questions on how to design digitalization to the benefit of companies and society.
baseurl: ""
url: "https://skymatic.de"

# Plugins
plugins:
  - jemoji
  - jekyll-redirect-from

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
emoji:
  src: "/img"
