# Site settings
title: Skymatic
feed:
  description: >
    Skymatic Blog
lang: en
baseurl: "" # the subpath of your site, e.g. /blog (must not end with /)

# Plugins
plugins:
  - jemoji
  - jekyll-redirect-from

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
